# Generated by Django 4.1.2 on 2022-10-14 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 15, 56, 10, 351543)),
        ),
    ]
