# Generated by Django 4.1.2 on 2022-10-15 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_createdon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 0, 43, 0, 151169)),
        ),
    ]
