# Generated by Django 4.1.2 on 2022-10-16 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_createdon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 16, 57, 18, 129206)),
        ),
    ]
