# Generated by Django 4.1.2 on 2022-10-16 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_createdon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isAdult',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 20, 43, 2, 23669)),
        ),
    ]
