# Generated by Django 4.1.2 on 2022-10-16 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_isadult_alter_profile_createdon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isAdult',
        ),
        migrations.AlterField(
            model_name='profile',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 20, 51, 32, 409478)),
        ),
    ]
